version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node build/src/index.js"


  db:
    image: mysql:8
    container_name: task-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: